---

- name: Propagate Mesos DEB package
  get_url: dest="/tmp/{{ mesos_package_name }}" url="{{ mesos_package_url }}/{{ mesos_package_name }}" force=yes

- name:
  package: name=/tmp/{{mesos_package_name}} state=present force=yes

- name: run ldconfig
  action: command /sbin/ldconfig

- name: Deploy init wrapper for Mesos
  copy: dest=/usr/bin/ src=mesos-init-wrapper force=yes mode=a+x

