---

- name: Install pip
  package:
  args:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items:
    - python-pip

- name: Upgrade pip
  pip: name=pip state=latest
  become: yes

# == Work Dir for replicated log
- name: Create work dir
  file: path={{ mesos_work_dir }} state=directory

- name: Create dirs
  file:
  args:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ mesos_cni_config_dir }}"
    - "{{ mesos_cni_plugins_dir }}"
    - "{{ mesos_modules_config_dir }}"
    - "{{ mesos_modules_libs_dir }}"
  when: mesos_install_mode == "slave"

# == Remove default configs
- name: Remove Default Mesos Configs
  file: state=absent path=/etc/mesos/

- name: Remove Default Mesos-Master Config
  file: state=absent path=/etc/mesos-master/

- name: Remove Default Mesos-Slave Config
  file: state=absent path=/etc/mesos-slave/

# == Configure and recreate
- name: Mesos default config file
  template: src=conf-mesos.j2 dest=/etc/default/mesos
  notify:
    - Restart mesos-master
    - Restart mesos-slave

- name: Mesos Master config file
  template: src=conf-mesos-master.j2 dest=/etc/default/mesos-master
  when: mesos_install_mode == "master" or mesos_install_mode == "slave"
  notify:
    - Restart mesos-master

- name: Mesos Slave config file
  template: src=conf-mesos-slave.j2 dest=/etc/default/mesos-slave
  when: mesos_install_mode == "slave" or mesos_install_mode == "slave"
  notify:
    - Restart mesos-slave

- file: path={{ slave_hook_module_path }} state=directory

- name: Check if upstart exists
  shell: /sbin/init --version | grep -q upstart
  register: etc_init
  failed_when: (etc_init.rc != 0) and (etc_init.rc != 1)

- file: path=/sbin/init state=touch

- name: Mesos master upstart script
  template: src=init-mesos-master.j2 dest=/etc/init/mesos-master.conf
  when: (mesos_install_mode == "master" or mesos_install_mode == "slave") and etc_init.rc == 0
  notify:
    - Restart mesos-master

- name: Mesos slave upstart script
  template: src=init-mesos-slave.j2 dest=/etc/init/mesos-slave.conf
  when: (mesos_install_mode == "master" or mesos_install_mode == "slave") and etc_init.rc == 0
  notify:
    - Restart mesos-slave

- name: Check if systemd exists
  stat: path=/bin/systemctl
  register: systemd_check

- name: Mesos master systemd script
  template: src=mesos-master.service.j2 dest=/etc/systemd/system/mesos-master.service
  when: (mesos_install_mode == "master" or mesos_install_mode == "slave") and systemd_check.stat.exists == true
  notify:
    - Reload daemon
    - Restart mesos-master

- name: Mesos slave systemd script
  template: src=mesos-slave.service.j2 dest=/etc/systemd/system/mesos-slave.service
  when: (mesos_install_mode == "slave" or mesos_install_mode == "slave") and systemd_check.stat.exists == true
  notify:
    - Reload daemon
    - Restart mesos-slave

