---

- name: Install control-node service (upstart)
  template: src="{{ item }}.upstart.j2" dest="/etc/init/{{ item }}.conf"
  with_items:
    - contrail-control
    - contrail-analytics
  notify:
    - restart contrail-control
    - restart contrail-analytics

- name: Copy images to master
  become: no
  shell: scp "{{ private_file_server }}:{{ contrail_images_path }}/{{ item }}" /tmp/
  with_items:
    - "{{ contrail_controler_image }}"
    - "{{ contrail_analytics_image }}"

- name: Load docker images
  shell: docker load < "/tmp/{{ item }}"
  with_items:
    - "{{ contrail_controler_image }}"
    - "{{ contrail_analytics_image }}"

- name: Start contrail-control service
  service: name="contrail-control" enabled=yes state=started

- name: Start contrail-analytics service
  service: name="contrail-analytics" enabled=yes state=started

- name: Wait for contrail-api
  wait_for:
  args:
    port: "{{ contrail_control_api_port }}"
    delay: 10

- name: Wait for contrail-dns
  wait_for:
  args:
    port: 8092
    delay: 10

- name: Retart contrail-names service
  command: docker exec contrail-control service contrail-named restart
