---

- name: Make sure necessary packages are installed
  become: yes
  local_action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - python-devel
    - python-netaddr
    - python-markupsafe
    - epel-release
    - vim-enhanced
  run_once: true
  retries: 3
  delay: 5
  register: result
  until: result|success
